(cl:in-package sick_safetyscanners-msg)
(cl:export '(UNSAFE_INPUTS_INPUT_SOURCES-VAL
          UNSAFE_INPUTS_INPUT_SOURCES
          UNSAFE_INPUTS_FLAGS-VAL
          UNSAFE_INPUTS_FLAGS
          MONITORING_CASE_NUMBER_INPUTS-VAL
          MONITORING_CASE_NUMBER_INPUTS
          MONITORING_CASE_NUMBER_INPUTS_FLAGS-VAL
          MONITORING_CASE_NUMBER_INPUTS_FLAGS
          LINEAR_VELOCITY_INPUTS_VELOCITY_0-VAL
          LINEAR_VELOCITY_INPUTS_VELOCITY_0
          LINEAR_VELOCITY_INPUTS_VELOCITY_0_VALID-VAL
          LINEAR_VELOCITY_INPUTS_VELOCITY_0_VALID
          LINEAR_VELOCITY_INPUTS_VELOCITY_0_TRANSMITTED_SAFELY-VAL
          LINEAR_VELOCITY_INPUTS_VELOCITY_0_TRANSMITTED_SAFELY
          LINEAR_VELOCITY_INPUTS_VELOCITY_1-VAL
          LINEAR_VELOCITY_INPUTS_VELOCITY_1
          LINEAR_VELOCITY_INPUTS_VELOCITY_1_VALID-VAL
          LINEAR_VELOCITY_INPUTS_VELOCITY_1_VALID
          LINEAR_VELOCITY_INPUTS_VELOCITY_1_TRANSMITTED_SAFELY-VAL
          LINEAR_VELOCITY_INPUTS_VELOCITY_1_TRANSMITTED_SAFELY
          SLEEP_MODE_INPUT-VAL
          SLEEP_MODE_INPUT
))