# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from main/ExtendedLaserScanMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import sensor_msgs.msg
import std_msgs.msg

class ExtendedLaserScanMsg(genpy.Message):
  _md5sum = "ebb40b28432208d7bfa749af849de1ab"
  _type = "main/ExtendedLaserScanMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """sensor_msgs/LaserScan laser_scan
bool[] reflektor_status
bool[] reflektor_median
bool[] intrusion


================================================================================
MSG: sensor_msgs/LaserScan
# Single scan from a planar laser range-finder
#
# If you have another ranging device with different behavior (e.g. a sonar
# array), please find or create a different message, since applications
# will make fairly laser-specific assumptions about this data

Header header            # timestamp in the header is the acquisition time of 
                         # the first ray in the scan.
                         #
                         # in frame frame_id, angles are measured around 
                         # the positive Z axis (counterclockwise, if Z is up)
                         # with zero angle being forward along the x axis
                         
float32 angle_min        # start angle of the scan [rad]
float32 angle_max        # end angle of the scan [rad]
float32 angle_increment  # angular distance between measurements [rad]

float32 time_increment   # time between measurements [seconds] - if your scanner
                         # is moving, this will be used in interpolating position
                         # of 3d points
float32 scan_time        # time between scans [seconds]

float32 range_min        # minimum range value [m]
float32 range_max        # maximum range value [m]

float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)
float32[] intensities    # intensity data [device-specific units].  If your
                         # device does not provide intensities, please leave
                         # the array empty.

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['laser_scan','reflektor_status','reflektor_median','intrusion']
  _slot_types = ['sensor_msgs/LaserScan','bool[]','bool[]','bool[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       laser_scan,reflektor_status,reflektor_median,intrusion

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ExtendedLaserScanMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.laser_scan is None:
        self.laser_scan = sensor_msgs.msg.LaserScan()
      if self.reflektor_status is None:
        self.reflektor_status = []
      if self.reflektor_median is None:
        self.reflektor_median = []
      if self.intrusion is None:
        self.intrusion = []
    else:
      self.laser_scan = sensor_msgs.msg.LaserScan()
      self.reflektor_status = []
      self.reflektor_median = []
      self.intrusion = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.laser_scan.header.seq, _x.laser_scan.header.stamp.secs, _x.laser_scan.header.stamp.nsecs))
      _x = self.laser_scan.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7f().pack(_x.laser_scan.angle_min, _x.laser_scan.angle_max, _x.laser_scan.angle_increment, _x.laser_scan.time_increment, _x.laser_scan.scan_time, _x.laser_scan.range_min, _x.laser_scan.range_max))
      length = len(self.laser_scan.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.laser_scan.ranges))
      length = len(self.laser_scan.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.laser_scan.intensities))
      length = len(self.reflektor_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.reflektor_status))
      length = len(self.reflektor_median)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.reflektor_median))
      length = len(self.intrusion)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(struct.Struct(pattern).pack(*self.intrusion))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.laser_scan is None:
        self.laser_scan = sensor_msgs.msg.LaserScan()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.laser_scan.header.seq, _x.laser_scan.header.stamp.secs, _x.laser_scan.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.laser_scan.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.laser_scan.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.laser_scan.angle_min, _x.laser_scan.angle_max, _x.laser_scan.angle_increment, _x.laser_scan.time_increment, _x.laser_scan.scan_time, _x.laser_scan.range_min, _x.laser_scan.range_max,) = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.laser_scan.ranges = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.laser_scan.intensities = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.reflektor_status = s.unpack(str[start:end])
      self.reflektor_status = list(map(bool, self.reflektor_status))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.reflektor_median = s.unpack(str[start:end])
      self.reflektor_median = list(map(bool, self.reflektor_median))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.intrusion = s.unpack(str[start:end])
      self.intrusion = list(map(bool, self.intrusion))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.laser_scan.header.seq, _x.laser_scan.header.stamp.secs, _x.laser_scan.header.stamp.nsecs))
      _x = self.laser_scan.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7f().pack(_x.laser_scan.angle_min, _x.laser_scan.angle_max, _x.laser_scan.angle_increment, _x.laser_scan.time_increment, _x.laser_scan.scan_time, _x.laser_scan.range_min, _x.laser_scan.range_max))
      length = len(self.laser_scan.ranges)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.laser_scan.ranges.tostring())
      length = len(self.laser_scan.intensities)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.laser_scan.intensities.tostring())
      length = len(self.reflektor_status)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.reflektor_status.tostring())
      length = len(self.reflektor_median)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.reflektor_median.tostring())
      length = len(self.intrusion)
      buff.write(_struct_I.pack(length))
      pattern = '<%sB'%length
      buff.write(self.intrusion.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.laser_scan is None:
        self.laser_scan = sensor_msgs.msg.LaserScan()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.laser_scan.header.seq, _x.laser_scan.header.stamp.secs, _x.laser_scan.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.laser_scan.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.laser_scan.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 28
      (_x.laser_scan.angle_min, _x.laser_scan.angle_max, _x.laser_scan.angle_increment, _x.laser_scan.time_increment, _x.laser_scan.scan_time, _x.laser_scan.range_min, _x.laser_scan.range_max,) = _get_struct_7f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.laser_scan.ranges = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.laser_scan.intensities = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.reflektor_status = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.reflektor_status = list(map(bool, self.reflektor_status))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.reflektor_median = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.reflektor_median = list(map(bool, self.reflektor_median))
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sB'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.intrusion = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
      self.intrusion = list(map(bool, self.intrusion))
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
