// Generated by gencpp from file sick_safetyscanners/ApplicationDataMsg.msg
// DO NOT EDIT!


#ifndef SICK_SAFETYSCANNERS_MESSAGE_APPLICATIONDATAMSG_H
#define SICK_SAFETYSCANNERS_MESSAGE_APPLICATIONDATAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sick_safetyscanners/ApplicationInputsMsg.h>
#include <sick_safetyscanners/ApplicationOutputsMsg.h>

namespace sick_safetyscanners
{
template <class ContainerAllocator>
struct ApplicationDataMsg_
{
  typedef ApplicationDataMsg_<ContainerAllocator> Type;

  ApplicationDataMsg_()
    : inputs()
    , outputs()  {
    }
  ApplicationDataMsg_(const ContainerAllocator& _alloc)
    : inputs(_alloc)
    , outputs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sick_safetyscanners::ApplicationInputsMsg_<ContainerAllocator>  _inputs_type;
  _inputs_type inputs;

   typedef  ::sick_safetyscanners::ApplicationOutputsMsg_<ContainerAllocator>  _outputs_type;
  _outputs_type outputs;





  typedef boost::shared_ptr< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ApplicationDataMsg_

typedef ::sick_safetyscanners::ApplicationDataMsg_<std::allocator<void> > ApplicationDataMsg;

typedef boost::shared_ptr< ::sick_safetyscanners::ApplicationDataMsg > ApplicationDataMsgPtr;
typedef boost::shared_ptr< ::sick_safetyscanners::ApplicationDataMsg const> ApplicationDataMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator1> & lhs, const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator2> & rhs)
{
  return lhs.inputs == rhs.inputs &&
    lhs.outputs == rhs.outputs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator1> & lhs, const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sick_safetyscanners

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2c1cd2050a13f8b7c83b35c17583a56";
  }

  static const char* value(const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2c1cd2050a13f8bULL;
  static const uint64_t static_value2 = 0x7c83b35c17583a56ULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_safetyscanners/ApplicationDataMsg";
  }

  static const char* value(const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ApplicationInputsMsg inputs\n"
"ApplicationOutputsMsg outputs\n"
"\n"
"================================================================================\n"
"MSG: sick_safetyscanners/ApplicationInputsMsg\n"
"bool[] unsafe_inputs_input_sources\n"
"bool[] unsafe_inputs_flags\n"
"\n"
"uint16[] monitoring_case_number_inputs\n"
"bool[] monitoring_case_number_inputs_flags\n"
"\n"
"int16 linear_velocity_inputs_velocity_0\n"
"bool linear_velocity_inputs_velocity_0_valid\n"
"bool linear_velocity_inputs_velocity_0_transmitted_safely\n"
"\n"
"int16 linear_velocity_inputs_velocity_1\n"
"bool linear_velocity_inputs_velocity_1_valid\n"
"bool linear_velocity_inputs_velocity_1_transmitted_safely\n"
"\n"
"uint8 sleep_mode_input\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sick_safetyscanners/ApplicationOutputsMsg\n"
"bool[] evaluation_path_outputs_eval_out\n"
"bool[] evaluation_path_outputs_is_safe\n"
"bool[] evaluation_path_outputs_is_valid\n"
"\n"
"uint16[] monitoring_case_number_outputs \n"
"bool[] monitoring_case_number_outputs_flags\n"
"\n"
"uint8 sleep_mode_output\n"
"bool sleep_mode_output_valid\n"
"\n"
"bool error_flag_contamination_warning\n"
"bool error_flag_contamination_error\n"
"bool error_flag_manipulation_error\n"
"bool error_flag_glare\n"
"bool error_flag_reference_contour_intruded\n"
"bool error_flag_critical_error\n"
"bool error_flags_are_valid\n"
"\n"
"\n"
"int16 linear_velocity_outputs_velocity_0\n"
"bool linear_velocity_outputs_velocity_0_valid\n"
"bool linear_velocity_outputs_velocity_0_transmitted_safely\n"
"\n"
"int16 linear_velocity_outputs_velocity_1\n"
"bool linear_velocity_outputs_velocity_1_valid\n"
"bool linear_velocity_outputs_velocity_1_transmitted_safely\n"
"\n"
"int16[] resulting_velocity\n"
"bool[] resulting_velocity_flags\n"
"\n"
" \n"
;
  }

  static const char* value(const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.inputs);
      stream.next(m.outputs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApplicationDataMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_safetyscanners::ApplicationDataMsg_<ContainerAllocator>& v)
  {
    s << indent << "inputs: ";
    s << std::endl;
    Printer< ::sick_safetyscanners::ApplicationInputsMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.inputs);
    s << indent << "outputs: ";
    s << std::endl;
    Printer< ::sick_safetyscanners::ApplicationOutputsMsg_<ContainerAllocator> >::stream(s, indent + "  ", v.outputs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SICK_SAFETYSCANNERS_MESSAGE_APPLICATIONDATAMSG_H
