// Generated by gencpp from file sick_safetyscanners/FieldData.msg
// DO NOT EDIT!


#ifndef SICK_SAFETYSCANNERS_MESSAGE_FIELDDATA_H
#define SICK_SAFETYSCANNERS_MESSAGE_FIELDDATA_H

#include <ros/service_traits.h>


#include <sick_safetyscanners/FieldDataRequest.h>
#include <sick_safetyscanners/FieldDataResponse.h>


namespace sick_safetyscanners
{

struct FieldData
{

typedef FieldDataRequest Request;
typedef FieldDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FieldData
} // namespace sick_safetyscanners


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sick_safetyscanners::FieldData > {
  static const char* value()
  {
    return "649f88740cfa9dc91cefbf73ed47045b";
  }

  static const char* value(const ::sick_safetyscanners::FieldData&) { return value(); }
};

template<>
struct DataType< ::sick_safetyscanners::FieldData > {
  static const char* value()
  {
    return "sick_safetyscanners/FieldData";
  }

  static const char* value(const ::sick_safetyscanners::FieldData&) { return value(); }
};


// service_traits::MD5Sum< ::sick_safetyscanners::FieldDataRequest> should match
// service_traits::MD5Sum< ::sick_safetyscanners::FieldData >
template<>
struct MD5Sum< ::sick_safetyscanners::FieldDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sick_safetyscanners::FieldData >::value();
  }
  static const char* value(const ::sick_safetyscanners::FieldDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_safetyscanners::FieldDataRequest> should match
// service_traits::DataType< ::sick_safetyscanners::FieldData >
template<>
struct DataType< ::sick_safetyscanners::FieldDataRequest>
{
  static const char* value()
  {
    return DataType< ::sick_safetyscanners::FieldData >::value();
  }
  static const char* value(const ::sick_safetyscanners::FieldDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sick_safetyscanners::FieldDataResponse> should match
// service_traits::MD5Sum< ::sick_safetyscanners::FieldData >
template<>
struct MD5Sum< ::sick_safetyscanners::FieldDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sick_safetyscanners::FieldData >::value();
  }
  static const char* value(const ::sick_safetyscanners::FieldDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sick_safetyscanners::FieldDataResponse> should match
// service_traits::DataType< ::sick_safetyscanners::FieldData >
template<>
struct DataType< ::sick_safetyscanners::FieldDataResponse>
{
  static const char* value()
  {
    return DataType< ::sick_safetyscanners::FieldData >::value();
  }
  static const char* value(const ::sick_safetyscanners::FieldDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SICK_SAFETYSCANNERS_MESSAGE_FIELDDATA_H
