// Generated by gencpp from file sick_safetyscanners/IntrusionDataMsg.msg
// DO NOT EDIT!


#ifndef SICK_SAFETYSCANNERS_MESSAGE_INTRUSIONDATAMSG_H
#define SICK_SAFETYSCANNERS_MESSAGE_INTRUSIONDATAMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sick_safetyscanners/IntrusionDatumMsg.h>

namespace sick_safetyscanners
{
template <class ContainerAllocator>
struct IntrusionDataMsg_
{
  typedef IntrusionDataMsg_<ContainerAllocator> Type;

  IntrusionDataMsg_()
    : data()  {
    }
  IntrusionDataMsg_(const ContainerAllocator& _alloc)
    : data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sick_safetyscanners::IntrusionDatumMsg_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sick_safetyscanners::IntrusionDatumMsg_<ContainerAllocator> >::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> const> ConstPtr;

}; // struct IntrusionDataMsg_

typedef ::sick_safetyscanners::IntrusionDataMsg_<std::allocator<void> > IntrusionDataMsg;

typedef boost::shared_ptr< ::sick_safetyscanners::IntrusionDataMsg > IntrusionDataMsgPtr;
typedef boost::shared_ptr< ::sick_safetyscanners::IntrusionDataMsg const> IntrusionDataMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator1> & lhs, const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator1> & lhs, const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sick_safetyscanners

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d061bbcb7871abcf1291e1a4e3b234a";
  }

  static const char* value(const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d061bbcb7871abcULL;
  static const uint64_t static_value2 = 0xf1291e1a4e3b234aULL;
};

template<class ContainerAllocator>
struct DataType< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sick_safetyscanners/IntrusionDataMsg";
  }

  static const char* value(const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "IntrusionDatumMsg[] data\n"
"\n"
"================================================================================\n"
"MSG: sick_safetyscanners/IntrusionDatumMsg\n"
"uint32 size\n"
"bool[] flags\n"
;
  }

  static const char* value(const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IntrusionDataMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sick_safetyscanners::IntrusionDataMsg_<ContainerAllocator>& v)
  {
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sick_safetyscanners::IntrusionDatumMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SICK_SAFETYSCANNERS_MESSAGE_INTRUSIONDATAMSG_H
