(cl:in-package main-msg)
(cl:export '(MULTIPLICATION_FACTOR-VAL
          MULTIPLICATION_FACTOR
          NUMBER_OF_BEAMS-VAL
          NUMBER_OF_BEAMS
          SCAN_TIME-VAL
          SCAN_TIME
          START_ANGLE-VAL
          START_ANGLE
          ANGULAR_BEAM_RESOLUTION-VAL
          ANGULAR_BEAM_RESOLUTION
          INTERBEAM_PERIOD-VAL
          INTERBEAM_PERIOD
))