(cl:in-package main-msg)
(cl:export '(VERSION_VERSION-VAL
          VERSION_VERSION
          VERSION_MAJOR_VERSION-VAL
          VERSION_MAJOR_VERSION
          VERSION_MINOR_VERSION-VAL
          VERSION_MINOR_VERSION
          VERSION_RELEASE-VAL
          VERSION_RELEASE
          SERIAL_NUMBER_OF_DEVICE-VAL
          SERIAL_NUMBER_OF_DEVICE
          SERIAL_NUMBER_OF_CHANNEL_PLUG-VAL
          SERIAL_NUMBER_OF_CHANNEL_PLUG
          CHANNEL_NUMBER-VAL
          CHANNEL_NUMBER
          SEQUENCE_NUMBER-VAL
          SEQUENCE_NUMBER
          SCAN_NUMBER-VAL
          SCAN_NUMBER
          TIMESTAMP_DATE-VAL
          TIMESTAMP_DATE
          TIMESTAMP_TIME-VAL
          TIMESTAMP_TIME
))