set(genlisp_SETUP_PY_SETUP_MODULE "distutils.core")
set(genlisp_SETUP_PY_VERSION "0.4.16")
set(genlisp_SETUP_PY_SCRIPTS "")
set(genlisp_SETUP_PY_PACKAGES "genlisp")
set(genlisp_SETUP_PY_PACKAGE_DIRS "src/genlisp")
set(genlisp_SETUP_PY_MODULES "")
set(genlisp_SETUP_PY_MODULE_DIRS "")