blacklist:
- rqt_rviz
- rviz_plugin_tutorials
- librviz_tutorial
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Release
devel_layout: linked
devel_space: devel
extend_path: null
install: true
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
