// Generated by gencpp from file main/ExtendedLaserScanMsg.msg
// DO NOT EDIT!


#ifndef MAIN_MESSAGE_EXTENDEDLASERSCANMSG_H
#define MAIN_MESSAGE_EXTENDEDLASERSCANMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/LaserScan.h>

namespace main
{
template <class ContainerAllocator>
struct ExtendedLaserScanMsg_
{
  typedef ExtendedLaserScanMsg_<ContainerAllocator> Type;

  ExtendedLaserScanMsg_()
    : laser_scan()
    , reflektor_status()
    , reflektor_median()
    , intrusion()  {
    }
  ExtendedLaserScanMsg_(const ContainerAllocator& _alloc)
    : laser_scan(_alloc)
    , reflektor_status(_alloc)
    , reflektor_median(_alloc)
    , intrusion(_alloc)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::LaserScan_<ContainerAllocator>  _laser_scan_type;
  _laser_scan_type laser_scan;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _reflektor_status_type;
  _reflektor_status_type reflektor_status;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _reflektor_median_type;
  _reflektor_median_type reflektor_median;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _intrusion_type;
  _intrusion_type intrusion;





  typedef boost::shared_ptr< ::main::ExtendedLaserScanMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main::ExtendedLaserScanMsg_<ContainerAllocator> const> ConstPtr;

}; // struct ExtendedLaserScanMsg_

typedef ::main::ExtendedLaserScanMsg_<std::allocator<void> > ExtendedLaserScanMsg;

typedef boost::shared_ptr< ::main::ExtendedLaserScanMsg > ExtendedLaserScanMsgPtr;
typedef boost::shared_ptr< ::main::ExtendedLaserScanMsg const> ExtendedLaserScanMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main::ExtendedLaserScanMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::main::ExtendedLaserScanMsg_<ContainerAllocator1> & lhs, const ::main::ExtendedLaserScanMsg_<ContainerAllocator2> & rhs)
{
  return lhs.laser_scan == rhs.laser_scan &&
    lhs.reflektor_status == rhs.reflektor_status &&
    lhs.reflektor_median == rhs.reflektor_median &&
    lhs.intrusion == rhs.intrusion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::main::ExtendedLaserScanMsg_<ContainerAllocator1> & lhs, const ::main::ExtendedLaserScanMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main::ExtendedLaserScanMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main::ExtendedLaserScanMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main::ExtendedLaserScanMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ebb40b28432208d7bfa749af849de1ab";
  }

  static const char* value(const ::main::ExtendedLaserScanMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xebb40b28432208d7ULL;
  static const uint64_t static_value2 = 0xbfa749af849de1abULL;
};

template<class ContainerAllocator>
struct DataType< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main/ExtendedLaserScanMsg";
  }

  static const char* value(const ::main::ExtendedLaserScanMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/LaserScan laser_scan\n"
"bool[] reflektor_status\n"
"bool[] reflektor_median\n"
"bool[] intrusion\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/LaserScan\n"
"# Single scan from a planar laser range-finder\n"
"#\n"
"# If you have another ranging device with different behavior (e.g. a sonar\n"
"# array), please find or create a different message, since applications\n"
"# will make fairly laser-specific assumptions about this data\n"
"\n"
"Header header            # timestamp in the header is the acquisition time of \n"
"                         # the first ray in the scan.\n"
"                         #\n"
"                         # in frame frame_id, angles are measured around \n"
"                         # the positive Z axis (counterclockwise, if Z is up)\n"
"                         # with zero angle being forward along the x axis\n"
"                         \n"
"float32 angle_min        # start angle of the scan [rad]\n"
"float32 angle_max        # end angle of the scan [rad]\n"
"float32 angle_increment  # angular distance between measurements [rad]\n"
"\n"
"float32 time_increment   # time between measurements [seconds] - if your scanner\n"
"                         # is moving, this will be used in interpolating position\n"
"                         # of 3d points\n"
"float32 scan_time        # time between scans [seconds]\n"
"\n"
"float32 range_min        # minimum range value [m]\n"
"float32 range_max        # maximum range value [m]\n"
"\n"
"float32[] ranges         # range data [m] (Note: values < range_min or > range_max should be discarded)\n"
"float32[] intensities    # intensity data [device-specific units].  If your\n"
"                         # device does not provide intensities, please leave\n"
"                         # the array empty.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::main::ExtendedLaserScanMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laser_scan);
      stream.next(m.reflektor_status);
      stream.next(m.reflektor_median);
      stream.next(m.intrusion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExtendedLaserScanMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main::ExtendedLaserScanMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::main::ExtendedLaserScanMsg_<ContainerAllocator>& v)
  {
    s << indent << "laser_scan: ";
    s << std::endl;
    Printer< ::sensor_msgs::LaserScan_<ContainerAllocator> >::stream(s, indent + "  ", v.laser_scan);
    s << indent << "reflektor_status[]" << std::endl;
    for (size_t i = 0; i < v.reflektor_status.size(); ++i)
    {
      s << indent << "  reflektor_status[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.reflektor_status[i]);
    }
    s << indent << "reflektor_median[]" << std::endl;
    for (size_t i = 0; i < v.reflektor_median.size(); ++i)
    {
      s << indent << "  reflektor_median[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.reflektor_median[i]);
    }
    s << indent << "intrusion[]" << std::endl;
    for (size_t i = 0; i < v.intrusion.size(); ++i)
    {
      s << indent << "  intrusion[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.intrusion[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_MESSAGE_EXTENDEDLASERSCANMSG_H
