// Generated by gencpp from file main/FieldDataRequest.msg
// DO NOT EDIT!


#ifndef MAIN_MESSAGE_FIELDDATAREQUEST_H
#define MAIN_MESSAGE_FIELDDATAREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace main
{
template <class ContainerAllocator>
struct FieldDataRequest_
{
  typedef FieldDataRequest_<ContainerAllocator> Type;

  FieldDataRequest_()
    {
    }
  FieldDataRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::main::FieldDataRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::main::FieldDataRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FieldDataRequest_

typedef ::main::FieldDataRequest_<std::allocator<void> > FieldDataRequest;

typedef boost::shared_ptr< ::main::FieldDataRequest > FieldDataRequestPtr;
typedef boost::shared_ptr< ::main::FieldDataRequest const> FieldDataRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::main::FieldDataRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::main::FieldDataRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace main

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::main::FieldDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::main::FieldDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main::FieldDataRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::main::FieldDataRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main::FieldDataRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::main::FieldDataRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::main::FieldDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::main::FieldDataRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::main::FieldDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "main/FieldDataRequest";
  }

  static const char* value(const ::main::FieldDataRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::main::FieldDataRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::main::FieldDataRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::main::FieldDataRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FieldDataRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::main::FieldDataRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::main::FieldDataRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAIN_MESSAGE_FIELDDATAREQUEST_H
