//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the sick_safetyscanners package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __sick_safetyscanners__SICKSAFETYSCANNERSCONFIGURATIONCONFIG_H__
#define __sick_safetyscanners__SICKSAFETYSCANNERSCONFIGURATIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace sick_safetyscanners
{
  class SickSafetyscannersConfigurationConfigStatics;

  class SickSafetyscannersConfigurationConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(SickSafetyscannersConfigurationConfig &config, const SickSafetyscannersConfigurationConfig &max, const SickSafetyscannersConfigurationConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const SickSafetyscannersConfigurationConfig &config1, const SickSafetyscannersConfigurationConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, SickSafetyscannersConfigurationConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const SickSafetyscannersConfigurationConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SickSafetyscannersConfigurationConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const SickSafetyscannersConfigurationConfig &config) const = 0;
      virtual void getValue(const SickSafetyscannersConfigurationConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T SickSafetyscannersConfigurationConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T SickSafetyscannersConfigurationConfig::* field;

      virtual void clamp(SickSafetyscannersConfigurationConfig &config, const SickSafetyscannersConfigurationConfig &max, const SickSafetyscannersConfigurationConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const SickSafetyscannersConfigurationConfig &config1, const SickSafetyscannersConfigurationConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, SickSafetyscannersConfigurationConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const SickSafetyscannersConfigurationConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SickSafetyscannersConfigurationConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const SickSafetyscannersConfigurationConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const SickSafetyscannersConfigurationConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, SickSafetyscannersConfigurationConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, SickSafetyscannersConfigurationConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<SickSafetyscannersConfigurationConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(SickSafetyscannersConfigurationConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("frame_id"==(*_i)->name){frame_id = boost::any_cast<std::string>(val);}
        if("skip"==(*_i)->name){skip = boost::any_cast<int>(val);}
        if("angle_start"==(*_i)->name){angle_start = boost::any_cast<double>(val);}
        if("angle_end"==(*_i)->name){angle_end = boost::any_cast<double>(val);}
        if("time_offset"==(*_i)->name){time_offset = boost::any_cast<double>(val);}
        if("expected_frequency"==(*_i)->name){expected_frequency = boost::any_cast<double>(val);}
        if("min_intensities"==(*_i)->name){min_intensities = boost::any_cast<double>(val);}
        if("channel_enabled"==(*_i)->name){channel_enabled = boost::any_cast<bool>(val);}
        if("general_system_state"==(*_i)->name){general_system_state = boost::any_cast<bool>(val);}
        if("derived_settings"==(*_i)->name){derived_settings = boost::any_cast<bool>(val);}
        if("measurement_data"==(*_i)->name){measurement_data = boost::any_cast<bool>(val);}
        if("intrusion_data"==(*_i)->name){intrusion_data = boost::any_cast<bool>(val);}
        if("application_io_data"==(*_i)->name){application_io_data = boost::any_cast<bool>(val);}
      }
    }

    std::string frame_id;
int skip;
double angle_start;
double angle_end;
double time_offset;
double expected_frequency;
double min_intensities;
bool channel_enabled;
bool general_system_state;
bool derived_settings;
bool measurement_data;
bool intrusion_data;
bool application_io_data;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string frame_id;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int skip;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_start;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double angle_end;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double time_offset;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double expected_frequency;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_intensities;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool channel_enabled;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool general_system_state;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool derived_settings;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool measurement_data;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool intrusion_data;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool application_io_data;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("SickSafetyscannersConfigurationConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const SickSafetyscannersConfigurationConfig &__max__ = __getMax__();
      const SickSafetyscannersConfigurationConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const SickSafetyscannersConfigurationConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const SickSafetyscannersConfigurationConfig &__getDefault__();
    static const SickSafetyscannersConfigurationConfig &__getMax__();
    static const SickSafetyscannersConfigurationConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const SickSafetyscannersConfigurationConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void SickSafetyscannersConfigurationConfig::ParamDescription<std::string>::clamp(SickSafetyscannersConfigurationConfig &config, const SickSafetyscannersConfigurationConfig &max, const SickSafetyscannersConfigurationConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class SickSafetyscannersConfigurationConfigStatics
  {
    friend class SickSafetyscannersConfigurationConfig;

    SickSafetyscannersConfigurationConfigStatics()
    {
SickSafetyscannersConfigurationConfig::GroupDescription<SickSafetyscannersConfigurationConfig::DEFAULT, SickSafetyscannersConfigurationConfig> Default("Default", "", 0, 0, true, &SickSafetyscannersConfigurationConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.frame_id = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.frame_id = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.frame_id = "scan";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<std::string>("frame_id", "str", 1, "Frame name of the laserscan topic", "", &SickSafetyscannersConfigurationConfig::frame_id)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<std::string>("frame_id", "str", 1, "Frame name of the laserscan topic", "", &SickSafetyscannersConfigurationConfig::frame_id)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.skip = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.skip = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.skip = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<int>("skip", "int", 1, "The number of scans to skip between each measured scan.  For a 25Hz laser, setting 'skip' to 0 makes it publish at 25Hz, 'skip' to 1 makes it publish at 12.5Hz.", "", &SickSafetyscannersConfigurationConfig::skip)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<int>("skip", "int", 1, "The number of scans to skip between each measured scan.  For a 25Hz laser, setting 'skip' to 0 makes it publish at 25Hz, 'skip' to 1 makes it publish at 12.5Hz.", "", &SickSafetyscannersConfigurationConfig::skip)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_start = -2.3998;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_start = 2.3998;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_start = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("angle_start", "double", 1, "Start angle for sensor in radians, if both start and end angle are 0, all angles are taken in account.", "", &SickSafetyscannersConfigurationConfig::angle_start)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("angle_start", "double", 1, "Start angle for sensor in radians, if both start and end angle are 0, all angles are taken in account.", "", &SickSafetyscannersConfigurationConfig::angle_start)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.angle_end = -2.3998;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.angle_end = 2.3998;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.angle_end = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("angle_end", "double", 1, "End angle for sensor in radians, if both start and end angle are 0, all angles are taken in account.", "", &SickSafetyscannersConfigurationConfig::angle_end)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("angle_end", "double", 1, "End angle for sensor in radians, if both start and end angle are 0, all angles are taken in account.", "", &SickSafetyscannersConfigurationConfig::angle_end)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.time_offset = -0.25;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.time_offset = 0.25;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.time_offset = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("time_offset", "double", 0, "An offset to add to the time stamp before publication of a scan [s].", "", &SickSafetyscannersConfigurationConfig::time_offset)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("time_offset", "double", 0, "An offset to add to the time stamp before publication of a scan [s].", "", &SickSafetyscannersConfigurationConfig::time_offset)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.expected_frequency = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.expected_frequency = 100.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.expected_frequency = 20.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("expected_frequency", "double", 0, "Expected scanner frequency.", "", &SickSafetyscannersConfigurationConfig::expected_frequency)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("expected_frequency", "double", 0, "Expected scanner frequency.", "", &SickSafetyscannersConfigurationConfig::expected_frequency)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_intensities = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_intensities = 255.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_intensities = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("min_intensities", "double", 0, "Minimum required intensities for valid measurement points", "", &SickSafetyscannersConfigurationConfig::min_intensities)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<double>("min_intensities", "double", 0, "Minimum required intensities for valid measurement points", "", &SickSafetyscannersConfigurationConfig::min_intensities)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.channel_enabled = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.channel_enabled = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.channel_enabled = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("channel_enabled", "bool", 8, "Enable Channel", "", &SickSafetyscannersConfigurationConfig::channel_enabled)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("channel_enabled", "bool", 8, "Enable Channel", "", &SickSafetyscannersConfigurationConfig::channel_enabled)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.general_system_state = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.general_system_state = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.general_system_state = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("general_system_state", "bool", 8, "Publish general system state", "", &SickSafetyscannersConfigurationConfig::general_system_state)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("general_system_state", "bool", 8, "Publish general system state", "", &SickSafetyscannersConfigurationConfig::general_system_state)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.derived_settings = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.derived_settings = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.derived_settings = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("derived_settings", "bool", 8, "Publish derived settings", "", &SickSafetyscannersConfigurationConfig::derived_settings)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("derived_settings", "bool", 8, "Publish derived settings", "", &SickSafetyscannersConfigurationConfig::derived_settings)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.measurement_data = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.measurement_data = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.measurement_data = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("measurement_data", "bool", 8, "Publish measurement data", "", &SickSafetyscannersConfigurationConfig::measurement_data)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("measurement_data", "bool", 8, "Publish measurement data", "", &SickSafetyscannersConfigurationConfig::measurement_data)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.intrusion_data = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.intrusion_data = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.intrusion_data = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("intrusion_data", "bool", 8, "Publish intrusion data", "", &SickSafetyscannersConfigurationConfig::intrusion_data)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("intrusion_data", "bool", 8, "Publish intrusion data", "", &SickSafetyscannersConfigurationConfig::intrusion_data)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.application_io_data = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.application_io_data = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.application_io_data = 1;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("application_io_data", "bool", 8, "Publish application io data", "", &SickSafetyscannersConfigurationConfig::application_io_data)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::ParamDescription<bool>("application_io_data", "bool", 8, "Publish application io data", "", &SickSafetyscannersConfigurationConfig::application_io_data)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(SickSafetyscannersConfigurationConfig::AbstractGroupDescriptionConstPtr(new SickSafetyscannersConfigurationConfig::GroupDescription<SickSafetyscannersConfigurationConfig::DEFAULT, SickSafetyscannersConfigurationConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<SickSafetyscannersConfigurationConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<SickSafetyscannersConfigurationConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    SickSafetyscannersConfigurationConfig __max__;
    SickSafetyscannersConfigurationConfig __min__;
    SickSafetyscannersConfigurationConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const SickSafetyscannersConfigurationConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static SickSafetyscannersConfigurationConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &SickSafetyscannersConfigurationConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const SickSafetyscannersConfigurationConfig &SickSafetyscannersConfigurationConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const SickSafetyscannersConfigurationConfig &SickSafetyscannersConfigurationConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const SickSafetyscannersConfigurationConfig &SickSafetyscannersConfigurationConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<SickSafetyscannersConfigurationConfig::AbstractParamDescriptionConstPtr> &SickSafetyscannersConfigurationConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<SickSafetyscannersConfigurationConfig::AbstractGroupDescriptionConstPtr> &SickSafetyscannersConfigurationConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const SickSafetyscannersConfigurationConfigStatics *SickSafetyscannersConfigurationConfig::__get_statics__()
  {
    const static SickSafetyscannersConfigurationConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = SickSafetyscannersConfigurationConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __SICKSAFETYSCANNERSCONFIGURATIONRECONFIGURATOR_H__
