set(gennodejs_SETUP_PY_SETUP_MODULE "distutils.core")
set(gennodejs_SETUP_PY_VERSION "2.0.1")
set(gennodejs_SETUP_PY_SCRIPTS "")
set(gennodejs_SETUP_PY_PACKAGES "gennodejs")
set(gennodejs_SETUP_PY_PACKAGE_DIRS "src/gennodejs")
set(gennodejs_SETUP_PY_MODULES "")
set(gennodejs_SETUP_PY_MODULE_DIRS "")